### ISSUE TITLE
ModuleNotFoundError: No module named 'Fitnet'

### ISSUE THREAD

**Issue by zkzssf** [xeanzheng/CSKD#1]
您好，我将预训练的教师模型放在saved model里面了，然后运行，发现报错：ModuleNotFoundError: No module named 'Fitnet'

一直不知道怎么解决
请问方便发一下 运行环境么 pytorch 版本 python版本 cuda 版本 等等 多谢

**Comment by xeanzheng** [comment]
更新了下文件，重新下载代码包应该就行了。
